package dev.galre.josue.akkaProject
package swagger

import akka.http.scaladsl.model.StatusCodes
import akka.http.scaladsl.server.Route
import com.github.swagger.akka.SwaggerHttpService

import scala.annotation.tailrec

/**
  * SwaggerHttpService along with swagger-ui.
  *
  * Swagger-UI is now delegated to https://petstore.swagger.io but with a 'url' parameter that points
  * at the 'swagger.json' generated by this example.
  */
trait SwaggerHttpWithUiService extends SwaggerHttpService {

  val swaggerUiRoute: Route = {
    pathPrefix(apiDocsPath) {
      val pathInit = removeTrailingSlashIfNecessary(apiDocsPath)
      redirect(
        s"https://petstore.swagger.io/?url=http://localhost:8080/$pathInit/swagger.json", StatusCodes
          .PermanentRedirect
      )
    }
  }

  override val routes: Route = super.routes ~ swaggerUiRoute

  @tailrec
  private def removeTrailingSlashIfNecessary(path: String): String =
    if (path.endsWith("/"))
      removeTrailingSlashIfNecessary(path.substring(0, path.length - 1))
    else path
}